config/routes.rb
Rails.application.routes.draw do
  resources :sangues
  get 'control_users/index'

  get 'welcome/index'

  root 'welcome#index'

  devise_for :users
  resources :users
  resources :faq
  resources :donors
  resources  :sangues


  get   '/sangue' => 'sangues#index'
  get '/welcome' => 'welcome#index'
  get '/faq' => 'faq#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donor.rb
class Donor < ApplicationRecord
  has_many :sangue 
end

app/models/sangue.rb
class Sangue < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:normal_user, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :donor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit

  protect_from_forgery with: :exception

rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

private

def user_not_authorized
  flash[:notice] = "Você não tem permissão para fazer esta ação"
  redirect_to(request.referrer || root_path)
end

end

app/controllers/control_users_controller.rb
class ControlUsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    authorize @users
  end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  before_action :set_donor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /donors
  # GET /donors.json
  def index
    @donors = Donor.all
    authorize @donors
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
  end

  # GET /donors/new
  def new
    @donor = Donor.new
  end

  # GET /donors/1/edit
  def edit
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(donor_params)

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.json { render :show, status: :created, location: @donor }
      else
        format.html { render :new }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donors/1
  # PATCH/PUT /donors/1.json
  def update
    respond_to do |format|
      if @donor.update(donor_params)
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { render :show, status: :ok, location: @donor }
      else
        format.html { render :edit }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor.destroy
    respond_to do |format|
      format.html { redirect_to donors_url, notice: 'Donor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donor
      @donor = Donor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donor_params
      params.require(:donor).permit(:nome, :idade, :email, :telefone, :cpf, :endereco, :tipo_sanguineo)
    end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
	def index 

	end
end

app/controllers/sangues_controller.rb
class SanguesController < ApplicationController
  before_action :set_sangue, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /sangues
  # GET /sangues.json
  def index
    @sangues = Sangue.all
    authorize @sangues
  end

  # GET /sangues/1
  # GET /sangues/1.json
  def show
  end

  # GET /sangues/new
  def new
    @sangue = Sangue.new
  end

  # GET /sangues/1/edit
  def edit
  end

  # POST /sangues
  # POST /sangues.json
  def create
    @sangue = Sangue.new(sangue_params)

    respond_to do |format|
      if @sangue.save
        format.html { redirect_to @sangue, notice: 'Sangue was successfully created.' }
        format.json { render :show, status: :created, location: @sangue }
      else
        format.html { render :new }
        format.json { render json: @sangue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sangues/1
  # PATCH/PUT /sangues/1.json
  def update
    respond_to do |format|
      if @sangue.update(sangue_params)
        format.html { redirect_to @sangue, notice: 'Sangue was successfully updated.' }
        format.json { render :show, status: :ok, location: @sangue }
      else
        format.html { render :edit }
        format.json { render json: @sangue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sangues/1
  # DELETE /sangues/1.json
  def destroy
    @sangue.destroy
    respond_to do |format|
      format.html { redirect_to sangues_url, notice: 'Sangue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sangue
      @sangue = Sangue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sangue_params
      params.require(:sangue).permit(:tipo, :quantidade)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_users_helper.rb
module ControlUsersHelper
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/sangues_helper.rb
module SanguesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/control_users/index.html.erb
<div class = "container">
<p id="notice"><%= notice %></p>

<h3>Usuários</h3>

<table class="striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Role</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<dev>
  <a class="waves-effect red accent-3 btn  " href = "/" >Voltar</a>
</dev>
</dev>

app/views/donors/_form.html.erb
<%= form_with(model: donor, local: true) do |form| %>
  <% if donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
      <% donor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
<form class = "col s8">
  <div class="row">
    <div class="input-field col s6">
      <%= form.label :nome %>
      <%= form.text_field :nome, id: :donor_nome %>
    </div>

    <div class="input-field col s2">
      <%= form.label :idade %>
      <%= form.number_field :idade, id: :donor_idade %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s5">
      <%= form.label :email %>
      <%= form.text_field :email, id: :donor_email %>
    </div>

    <div class="input-field col s3">
      <%= form.label :telefone %>
      <%= form.text_field :telefone, id: :donor_telefone %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s5">
        <%= form.label :cpf %>
        <%= form.text_field :cpf, id: :donor_cpf %>
      </div>

      <div class="input-field col s3">
        <%= form.label :tipo_sanguineo %>
        <%= form.text_field :tipo_sanguineo, id: :donor_tipo_sanguineo %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s8">
        <%= form.label :endereco %>
        <%= form.text_field :endereco, id: :donor_endereco %>
      </div>
    </div>

  <div>
    <a class="waves-effect red accent-3 btn  "><%= form.submit %></a>
  </div>
</form>
</div>
<% end %>

app/views/donors/edit.html.erb
<div class = "container">
<h3>Editar Cadastro</h3>

<%= render 'form', donor: @donor %>

<span class="waves-effect red accent-3 btn"><%= link_to 'Mostrar', @donor %></span>
|<a class="waves-effect red accent-3 btn" href= "/">Voltar</a>
<br>

</div>

app/views/donors/index.html.erb
<p id="notice"><%= notice %></p>
<div class = "container">
<h3>Doadores</h3>

<table class="striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Cpf</th>
      <th>Endereco</th>
      <th>Tipo sanguineo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donors.each do |donor| %>
      <tr>
        <td><%= donor.nome %></td>
        <td><%= donor.idade %></td>
        <td><%= donor.email %></td>
        <td><%= donor.telefone %></td>
        <td><%= donor.cpf %></td>
        <td><%= donor.endereco %></td>
        <td><%= donor.tipo_sanguineo %></td>
        <td><%= link_to 'Mostrar', donor %></td>
        <td><%= link_to 'Editar', edit_donor_path(donor) %></td>
        <td><%= link_to 'Deletar', donor, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div>
  <a class="waves-effect red accent-3 btn  " href = <%= new_donor_path %> >Novo Cadastro</a>
</div>
<br>
<div>
<a class="waves-effect red accent-3 btn  " href = "/">Voltar</a>
</div>

app/views/donors/new.html.erb
<div class = "container">
<h1>Cadastrar Doador</h1>

<%= render 'form', donor: @donor %>
 <div>
    <a class="waves-effect red accent-3 btn " href = "/" >Voltar</a>
  </div>
    
</div>

app/views/donors/show.html.erb
<div class = "container">
<p id="notice"><%= notice %></p>
<h3>Doador</h3>
<table>
<p>
  <strong>Nome:</strong>
  <%= @donor.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @donor.idade %>
</p>

<p>
  <strong>Email:</strong>
  <%= @donor.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @donor.telefone %>
</p>

<p>
  <strong>CPF:</strong>
  <%= @donor.cpf %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @donor.endereco %>
</p>

<p>
  <strong>Tipo sanguineo:</strong>
  <%= @donor.tipo_sanguineo %>
</p>
</table>
 <span class="waves-effect red accent-3 btn"><%= link_to 'Editar', edit_donor_path(@donor) %></span> | <a class="waves-effect red accent-3 btn" href="/">Voltar</a>
</div>

<!-- <%= link_to 'Voltar', donors_path %> -->

app/views/faq/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>FAQ</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
<body>

<div class = "container">
 <h2><strong><em>FAQ</em></strong></h2>

<h3><strong><em></em>Quem pode doar?</strong></h3>
 <blockquote>
 <h6 class="flow-text">Qualquer pessoa com idade entre 18 e 67 anos que pese mais de 50 quilos. Jovens de 16 ou 17 anos também estão aptos, desde que tenham o consentimento dos pais ou dos responsáveis.</h6>
 </blockquote>

<h3><strong><em></em>Quanto tempo demora?</strong></h3>
 <blockquote>
 <h6 class="flow-text">A coleta do sangue é bem rápida: leva de 8 a 12 minutos. Antes, o doador faz uma triagem e passa algumas informações de saúde para os funcionários do local.</h6>
</blockquote>

<h3><strong><em></em>Quanto sangue é retirado?</strong></h3>
 <blockquote>
 <h6 class="flow-text">São 450 mililitros. Esse volume pode salvar a vida de até quatro pessoas.</h6>
</blockquote>

 <h3><strong><em></em>O procedimento oferece algum perigo?</strong></h3>
 <blockquote>
 <h6 class="flow-text" >Não. A doação é totalmente segura e não apresenta nenhum risco. Os materiais utilizados, como a agulha e os cateteres, são descartáveis.</h6>
 </blockquote>

 <h3><strong><em></em>Mas meu corpo não vai sentir falta desse sangue?</strong></h3>
 <blockquote>
 <h6 class="flow-text">Não. Nós possuímos cerca de 5 litros do líquido vermelho circulando pelos vasos. A retirada não prejudica em nada: o organismo repõe e alcança os níveis normais em até 72 horas.</h6>
</blockquote>

 <h3><strong><em></em>Onde eu posso doar?</strong></h3>
 <blockquote>
 <h6 class="flow-text">Nos principais hospitais e hemocentros próximos da sua casa. Para mais informações, acesse o site do Ministério da Saúde ou das secretarias de saúde estaduais e municipais.
 </h6>
</blockquote>

<h3><strong><em></em>Existem algumas doenças que impedem a doação de sangue?</strong></h3>
 <blockquote>
 <h6 class="flow-text">Sim. Doenças infecciosas, como a gripe, e inflamatórias, como aquelas que atacam o intestino, exigem que a doação seja postergada para outra data. Em caso de dúvida, converse com o profissional de saúde do hemocentro para saber se tudo está ok.
 </h6>
 </blockquote>

 <h3><strong><em></em>E o que eu preciso levar no dia da doação?</strong></h3>
 <blockquote>
 <h6 class="flow-text">Apenas um documento original com foto.</h6>
</blockquote>

 <h3><strong><em></em>Eu fiz uma cirurgia recentemente. Posso doar sangue?</strong></h3>
 <blockquote>
 <h6 class="flow-text">Você deve esperar 72 horas para doar sangue após uma extração dentária. Operações simples, como apendicite e retirada de varizes, pedem 3 meses. Procedimentos mais complexos, como a remoção da tireoide ou de um rim, meio ano. Caso você tenha passado por uma transfusão de sangue ou fez uma tatuagem, é importante aguardar por um ano.</h6>
</blockquote>

 <h3><strong><em></em>E quanto tempo eu tenho que esperar entre uma doação e outra? </strong></h3>
 <blockquote>
 <h6 class="flow-text">Os homens podem visitar o banco de sangue a cada 60 dias. Já as mulheres devem aguardar três meses.
 </h6>
</blockquote>

 <h3><strong><em></em>E depois de doar sangue? Devo seguir alguma recomendação médica?</strong></h3>
 <blockquote>
 <h6 class="flow-text">Sim. Evite esforços físicos, beba bastante água, não fume por duas horas e evite ingerir álcool pelo resto do dia. Também é importante não praticar esportes radicais, como paraquedismo ou mergulho, ou dirigir veículos de grande porte.</h6>
</blockquote>

<h3><strong><em></em>A taxa de doações no Brasil é baixa?</strong></h3>
 <blockquote>
 <h6 class="flow-text">De acordo com os dados mais recentes do Ministério da Saúde, os brasileiros produzem 3,6 milhões de bolsas de sangue todos os anos. Isso significa que 1,8% da população é doadora. Nós estamos dentro dos parâmetros da Organização Mundial da Saúde: eles pedem que 1 a 3% do país tenha o costume de deixar a sua contribuição nos hemocentros. Mas os especialistas garantem que esse número precisa subir. Que tal ser um doador de sangue?</h6>
</blockquote>

<h3><strong><em></em>Doar sangue engrossa ou afina o sangue?</strong></h3>
  <blockquote>
 <h6 class="flow-text">Não engrossa nem afina o sangue, é apenas um mito.</h6>
</blockquote>

<h3><strong><em></em>Fiz uma tatuagem há um ano. Posso doar?</strong></h3>
 <blockquote>
 <h6 class="flow-text">Sim. Quem fez tatuagem há mais de um ano pode doar sangue.</h6>
</blockquote>

<h3><strong><em></em> O que é feito com o sangue que doamos?</strong></h3>
 <blockquote>
 <h6 class="flow-text">Após a coleta, a bolsa coletada é fracionada em componentes sangüíneos (concentrado de hemácias, de plaquetas e plasma). Esses componentes são liberados para uso somente após o resultado dos exames. As unidades que apresentam reatividade sorológica são descartadas. Uma única unidade doada pode beneficiar três pacientes.
 </h6>
 </blockquote>

<h3><strong><em></em>Doar sangue dói?</strong></h3>
  <blockquote>
 <h6 class="flow-text">Não.</h6>
</blockquote>

<h3><strong><em></em>O que acontece se uma pessoa que não sabe se está anêmica quiser doar sangue?</strong></h3>
 <blockquote>
 <h6 class="flow-text">O candidato à doação é atendido por um profissional do Serviço de Hemoterapia, que realiza um teste rápido para verificar se o doador está ou não anêmico.</h6>
</blockquote>

<h3><strong><em></em>O uso de medicamento pode impedir alguém de doar?</strong></h3>
 <blockquote>
 <h6 class="flow-text">O uso de medicamento deve ser analisado caso a caso. Portanto, antes de doar consulte o Serviço de Hemoterapia.</h6>
</blockquote>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

      <title>Hemocentro</title>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  <% if user_signed_in? %>
  <% if current_user.admin? %>


  <nav>
    <div class="nav-wrapper red accent-3">
      <a class="brand-logo"><a href="/welcome" class="btn btn-floating btn-large red darken-2 pulse"><i class="material-icons ">home</i></a></a>
      <ul class="right hide-on-med-and-down">
      <li><a href = "/sangues">Banco de Sangue</a></li>
        <li><%= link_to "Doadores", donors_path %></li>
       <li><%= link_to "Usuarios", control_users_index_path %></li>
        <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
        <li><a href="/faq">FAQ</a></li>
      </ul>
    </div>
  </nav>


  <%else%>

    <nav>
    <div class="nav-wrapper red accent-3">
      <a class="brand-logo"><a href="/welcome" class="btn btn-floating btn-large red darken-2 pulse"><i class="material-icons ">home</i></a></a>
      <ul class="right hide-on-med-and-down">
       <li><%= link_to "Cadastrar Doador", new_donor_path %></li>
        <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
        <li><a href="/faq">FAQ</a></li>
      </ul>
    </div>
  </nav>

<% end %>

<% else %>

  	<nav>
    <div class="nav-wrapper red accent-3">
      <a class="brand-logo"><a href="/welcome" class="btn btn-floating btn-large red darken-2 pulse"><i class="material-icons ">home</i></a></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/users/sign_up">Cadastro</a></li>
        <li><a href="/users/sign_in">Login</a></li>
        <li><a href="/faq">FAQ</a></li>
      </ul>
    </div>
  </nav>

<% end %>


 <%= yield %>

</body>

</html>

app/views/sangues/_form.html.erb
<%= form_with(model: sangue, local: true) do |form| %>
  <% if sangue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sangue.errors.count, "error") %> prohibited this sangue from being saved:</h2>

      <ul>
      <% sangue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <form class = "col s8">
      <div class="row">
        <div class="input-field col s6">
          <%= form.label :tipo %>
          <%= form.text_field :tipo, id: :sangue_tipo %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6">
    <%= form.label :quantidade %>
    <%= form.number_field :quantidade, id: :sangue_quantidade %>
  </div>
</div>

 <div class="actions">
<span class="waves-effect red accent-3 btn">
    <%= form.submit %>
    </span>

</form>
</div>


 
<% end %>
 <br>

app/views/sangues/edit.html.erb
<div class = "container">
<h3>Editar</h3>

<%= render 'form', sangue: @sangue %>

<span class="waves-effect red accent-3 btn"><%= link_to 'Mostrar', @sangue %></span> |
<span class="waves-effect red accent-3 btn"><%= link_to 'Voltar', sangues_path %></span>
</div>

app/views/sangues/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Sangues Disponiveis:</h1>

<table class="striped">
  <thead>
    <tr>
      <th>Tipos</th>
      <th>Quantidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @sangues.each do |sangue| %>
      <tr>
        <td><%= sangue.tipo %></td>
        <td><%= sangue.quantidade %></td>
        <td><%= link_to 'Mostrar', sangue %></td>
        <td><%= link_to 'Editar', edit_sangue_path(sangue) %></td>
        <td><%= link_to 'Deletar', sangue, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<span class="waves-effect red accent-3 btn"><%= link_to 'New Sangue', new_sangue_path %></span>
<a class="waves-effect red accent-3 btn" href = '/'> voltar</a>

</div>

app/views/sangues/new.html.erb
<div class = "container">
<h1>Sangue</h1>

<%= render 'form', sangue: @sangue %>

<span class="waves-effect red accent-3 btn"><%= link_to 'Voltar', sangues_path %></span>
</div>

app/views/sangues/show.html.erb
<div class = "container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @sangue.tipo %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @sangue.quantidade %>
</p>

<span class="waves-effect red accent-3 btn"><%= link_to 'Editar', edit_sangue_path(@sangue) %></span> |
<span class="waves-effect red accent-3 btn"><%= link_to 'Voltar', sangues_path %></span>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Entrar", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Cadastrar-se", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu a senha?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
	<meta charset="UTF-8">
</head>
<body>

<div class = "center">
	<h1><img src="Terceiro.jpg"></h1>
</div>


<div class = "container">

 <h3><strong><em>Porque doar sangue?</em></strong></h3>
 <blockquote>
 <p class="flow-text"><font size = "4" >O sangue é um tecido conjuntivo produzido pela medula óssea que
    realiza várias funções no organismo. É composto por plasma, glóbulos brancos, glóbulos vermelhos, hemácias, plaquetas, sais, vitaminas, água e fatores de coagulação.

    A doação de sangue consiste em um ato voluntário de permitir a retirada do seu próprio sangue para beneficiar as pessoas que necessitam receber sangue por qualquer motivo. Infelizmente ainda não foi encontrado nenhum substituto para o sangue, ou seja, é um tecido de extrema importância e valor, pois a sua ausência resulta em morte.

    Para doar sangue o indivíduo preenche um cadastro com seus dados pessoais para que seja cadastrado como doador e ainda para que seja produzida sua carteira de doador. Após o cadastro o mesmo é levado até um profissional que irá verificar seu peso, batimentos cardíacos e pressão arterial. Depois é submetido a exames e à triagem clínica, onde responde perguntas importantes sobre sua condição física.

    Depois de realizados todos os procedimentos necessários, o indivíduo que estiver apto a doar sangue é encaminhado à sala de coleta, onde são retirados 450 ml de sangue do seu braço. Após a doação um lanche é servido ao doador que precisará tomar muito líquido no decorrer do dia.

    A bolsa que recebe o sangue retirado é encaminhada ao fracionamento, onde será separada em até quatro componentes (hemácias, plasmas, plaquetas e fatores de coagulação) que em seguida são levados ao local onde serão armazenados até que sua utilização seja necessária.

    O indivíduo ao doar sangue não apresenta nenhuma manifestação corpórea. Os cuidados após a coleta são: evitar dobrar o braço pelo qual o sangue foi retirado, evitar esforço físico no dia da coleta, manter o curativo por até quatro horas, não fumar nas primeiras duas horas e não ingerir bebidas alcoólicas nas próximas doze horas.
	</font>
	</p>
</blockquote>
  </div>

<div class = "container">
  <h3>Tipos sanguíneos:</h3>

  <table class="striped">
        <thead>
          <tr>
              <td>A+</td>
              <td>A-</td>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>B+</td>
             <td>B-</td>

          </tr>
           </tr>
          <tr>
            <td>AB+</td>
            <td>AB-</td>

          </tr>
          <tr>
            <td>O+</td>
             <td>O-</td>

          </tr>
        </tbody>
      </table>
            </div>

            <div class="container">

<h3>Compatibilidade Sanguínea:</h3>

<div class = "center"><img class="materialboxed" data-caption="Sistema ABO de Grupos Sanguíneos" src="Relacoes.jpeg"></div>

</div>
</body>
</html>